version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:${REDIS_PORT}/${REDIS_DB}
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    shm_size: 1g
    networks:
      - app_network

  redis:
    image: redis:7.2-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    command: npm start

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge